/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.panels;

import com.jdbc.ConexionJDBC;
import com.models.Producto;
import com.models.Usuario;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
 *
 * @author Jenny
 */
public class Productos extends javax.swing.JPanel {
    ConexionJDBC con;
    /**
     * Creates new form Productos
     */
    public Productos() {
        initComponents();
        cargar_datos();
        this.lbl_message.setVisible(false);
    }
    private void cargar_datos(){
        con = new ConexionJDBC();
        DefaultTableModel model;
        List<Producto> productos;
        productos = new ArrayList<>();
        Producto producto;
        int count = 0;
        try {
                Statement query = con.getConexion().createStatement();
                ResultSet res = query.executeQuery("Select * from productos");
                
               
                while (res.next()){     
                    producto = new Producto(res.getInt("ID_PRODUCTO"),res.getString("DESCRIPCION"), res.getDouble("PRECIO"));
                  productos.add(producto);
                }
             
                con.getConexion().close();
             
                
            } catch (SQLException ex) {
                throw new RuntimeException(ex);
            }  
       
        if (productos.size() > 0){
            model = new DefaultTableModel(new String[]{"ID","Descripción","Precio"}, productos.size());        
            this.tb_productos.setModel(model);
             System.out.println(productos.size());
             
             TableModel t_model = this.tb_productos.getModel();
             for(int i=0; i< productos.size(); i++){
                 Producto _prod = productos.get(i);
                 t_model.setValueAt(_prod.getID_PRODUCTO(), i, 0);
                 t_model.setValueAt(_prod.getDESCRIPCION(), i, 1);
                 t_model.setValueAt(_prod.getPRECIO(), i, 2);
             }
             
        }
    }
    public void clearForm(){
        this.txt_descripcion.setText("");
        this.txt_id.setText("");
        this.txt_precio.setText("");
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_producto = new javax.swing.JPanel();
        sp_contenedor = new javax.swing.JScrollPane();
        tb_productos = new javax.swing.JTable();
        jp_productos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_idProducto = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_descripcion = new javax.swing.JTextField();
        lbl_descripcion = new javax.swing.JLabel();
        lbl_precio = new javax.swing.JLabel();
        txt_precio = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        lbl_message = new javax.swing.JLabel();
        btn_update = new javax.swing.JButton();
        btn_insert = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();

        tb_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        sp_contenedor.setViewportView(tb_productos);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setText("Producto");

        lbl_idProducto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_idProducto.setText("Código");

        lbl_descripcion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_descripcion.setText("Descripción");

        lbl_precio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_precio.setText("Precio");

        txt_precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_precioActionPerformed(evt);
            }
        });

        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-search-more-36.png"))); // NOI18N
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        lbl_message.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_message.setForeground(new java.awt.Color(255, 204, 0));
        lbl_message.setText("No se ha encontrado ningún producto con ese identificador");

        javax.swing.GroupLayout jp_productosLayout = new javax.swing.GroupLayout(jp_productos);
        jp_productos.setLayout(jp_productosLayout);
        jp_productosLayout.setHorizontalGroup(
            jp_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_productosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_productosLayout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jLabel1)
                        .addGap(589, 589, 589))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_productosLayout.createSequentialGroup()
                        .addGroup(jp_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jp_productosLayout.createSequentialGroup()
                                .addComponent(lbl_idProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_message, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jp_productosLayout.createSequentialGroup()
                                .addGroup(jp_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jp_productosLayout.createSequentialGroup()
                                        .addComponent(lbl_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_precio))
                                    .addGroup(jp_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jp_productosLayout.createSequentialGroup()
                                            .addComponent(lbl_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txt_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 133, Short.MAX_VALUE)))
                        .addGap(372, 372, 372))))
        );
        jp_productosLayout.setVerticalGroup(
            jp_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_productosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jp_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_productosLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lbl_message, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addGroup(jp_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_idProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jp_productosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btn_update.setText("ACTUALIZAR");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_insert.setText("INSERTAR");
        btn_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertActionPerformed(evt);
            }
        });

        btn_delete.setText("ELIMINAR");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_productoLayout = new javax.swing.GroupLayout(jp_producto);
        jp_producto.setLayout(jp_productoLayout);
        jp_productoLayout.setHorizontalGroup(
            jp_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sp_contenedor)
            .addGroup(jp_productoLayout.createSequentialGroup()
                .addComponent(jp_productos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jp_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_update, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_delete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
            .addGroup(jp_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_productoLayout.createSequentialGroup()
                    .addContainerGap(736, Short.MAX_VALUE)
                    .addComponent(btn_insert, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20)))
        );
        jp_productoLayout.setVerticalGroup(
            jp_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_productoLayout.createSequentialGroup()
                .addGroup(jp_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jp_productos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jp_productoLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sp_contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE))
            .addGroup(jp_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jp_productoLayout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(btn_insert, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(439, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_producto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_producto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_precioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_precioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_precioActionPerformed

    private void btn_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertActionPerformed
        Producto prod =  new Producto(Integer.parseInt(this.txt_id.getText()),this.txt_descripcion.getText() ,Double.parseDouble(this.txt_precio.getText()));
        if(prod.insert()){
            this.clearForm();
            this.cargar_datos();
             JOptionPane.showMessageDialog(null, "Se ha creado correctamente",
                "Válido", JOptionPane.PLAIN_MESSAGE); 
        }else{
            JOptionPane.showMessageDialog(null, "No se ha guardado el registro",
                "Error", JOptionPane.ERROR_MESSAGE); 
        }
        
    }//GEN-LAST:event_btn_insertActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
       Producto _prod = new Producto();
       this.btn_insert.setEnabled(false);
       _prod.consultar(Integer.parseInt(this.txt_id.getText()));
       if(_prod.getDESCRIPCION()== null ||_prod.getDESCRIPCION().equals("")){
           this.lbl_message.setVisible(true);
       }else{
           this.lbl_message.setVisible(false);
            this.txt_id.setText(String.valueOf(_prod.getID_PRODUCTO()));
            this.txt_precio.setText( String.valueOf(_prod.getPRECIO() ));
            this.txt_descripcion.setText(_prod.getDESCRIPCION());
       }
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        Producto _prod = new Producto();
        if(_prod.delete(this.txt_id.getText())){
            this.clearForm();
            this.cargar_datos();
            this.btn_insert.setEnabled(true);
            JOptionPane.showMessageDialog(null, "Se ha eliminado correctamente",
                "Válido", JOptionPane.PLAIN_MESSAGE); 
            
        }else{
            JOptionPane.showMessageDialog(null, "No se ha eliminado el registro",
                "Error", JOptionPane.ERROR_MESSAGE); 
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        Producto _prod =  new Producto(Integer.parseInt(this.txt_id.getText()),this.txt_descripcion.getText() ,Double.parseDouble(this.txt_precio.getText()));
        if(_prod.update()){
            this.clearForm();
            this.cargar_datos();
            this.btn_insert.setEnabled(true);
            JOptionPane.showMessageDialog(null, "Se ha actualizado el producto correctamente",
                "Válido", JOptionPane.PLAIN_MESSAGE); 
            
        }else{
            JOptionPane.showMessageDialog(null, "No se ha completado la actualizacion de los datos del producto",
                "Error", JOptionPane.ERROR_MESSAGE); 
        }
    }//GEN-LAST:event_btn_updateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_insert;
    private javax.swing.JButton btn_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jp_producto;
    private javax.swing.JPanel jp_productos;
    private javax.swing.JLabel lbl_descripcion;
    private javax.swing.JLabel lbl_idProducto;
    private javax.swing.JLabel lbl_message;
    private javax.swing.JLabel lbl_precio;
    private javax.swing.JScrollPane sp_contenedor;
    private javax.swing.JTable tb_productos;
    private javax.swing.JTextField txt_descripcion;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_precio;
    // End of variables declaration//GEN-END:variables
}
