/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.panels;

import com.jdbc.ConexionJDBC;
import com.models.Producto;
import com.models.Usuario;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
 *
 * @author developer
 */
public class Usuarios extends javax.swing.JPanel {
    ConexionJDBC con;
    Usuario user;
    
    /**
     * Creates new form Productos
     */
    public Usuarios() {
        initComponents();
        cargar_datos();
       
        this.lbl_message.setVisible(false);
        this.btn_delete.setVisible(false);
    }
    private void cargar_datos(){
        con = new ConexionJDBC();
        DefaultTableModel model;
        List<Usuario> usuarios;
        usuarios = new ArrayList<>();
        Usuario usuario;
        int count = 0;
        try {
                Statement query = con.getConexion().createStatement();
                ResultSet res = query.executeQuery("Select * from usuario");
                
               
                while (res.next()){     
                    usuario = new Usuario(res.getString("DNI"),res.getString("Nombre"),
                            res.getString("Apellidos"), res.getString("Direccion_1"),res.getString("Direccion_2"));
                  usuarios.add(usuario);
                }
             
                con.getConexion().close();
             
                
            } catch (SQLException ex) {
                throw new RuntimeException(ex);
            }  
       
        if (usuarios.size() > 0){
            model = new DefaultTableModel(new String[]{"DNI","Nombre","Apellidos","Direccion_1","Direccion_2"}, usuarios.size());        
            this.tb_usuarios.setModel(model);
             System.out.println(usuarios.size());
             
             TableModel t_model = this.tb_usuarios.getModel();
             for(int i=0; i< usuarios.size(); i++){
                 Usuario _user = usuarios.get(i);
                 t_model.setValueAt(_user.getDni(), i, 0);
                 t_model.setValueAt(_user.getNombre(), i, 1);
                 t_model.setValueAt(_user.getDireccion1(), i, 2);
                 t_model.setValueAt(_user.getDireccion2(), i, 3);
             }
             
        }
    }
    public void clearForm(){
        this.txt_dni.setText("");
        this.txt_nombre.setText("");
        this.txt_apellidos.setText("");
        this.txt_direccion1.setText("");
        this.txt_direccion2.setText("");
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_usuario = new javax.swing.JPanel();
        sp_contenedor = new javax.swing.JScrollPane();
        tb_usuarios = new javax.swing.JTable();
        jp_usuarios = new javax.swing.JPanel();
        jLUsuario = new javax.swing.JLabel();
        lbl_dni = new javax.swing.JLabel();
        txt_dni = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        lbl_nombre = new javax.swing.JLabel();
        lbl_apellidos = new javax.swing.JLabel();
        txt_apellidos = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        lbl_message = new javax.swing.JLabel();
        txt_direccion1 = new javax.swing.JTextField();
        lbl_direccion1 = new javax.swing.JLabel();
        javax.swing.JLabel lbl_direccion2 = new javax.swing.JLabel();
        txt_direccion2 = new javax.swing.JTextField();
        btn_update = new javax.swing.JButton();
        btn_insert = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();

        tb_usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dni", "Nombre", "Apellidos", "Dirección1", "Direccion2"
            }
        ));
        sp_contenedor.setViewportView(tb_usuarios);

        jLUsuario.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLUsuario.setText("Usuario");

        lbl_dni.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_dni.setText("Dni");

        txt_dni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dniActionPerformed(evt);
            }
        });

        lbl_nombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_nombre.setText("Nombre");

        lbl_apellidos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_apellidos.setText("Apellidos");

        txt_apellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_apellidosActionPerformed(evt);
            }
        });

        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-search-more-36.png"))); // NOI18N
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        lbl_message.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_message.setForeground(new java.awt.Color(255, 204, 0));
        lbl_message.setText("No se ha encontrado ningún producto con ese identificador");

        txt_direccion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_direccion1ActionPerformed(evt);
            }
        });

        lbl_direccion1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_direccion1.setText("Direccion1");

        lbl_direccion2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_direccion2.setText("Direccion2");

        txt_direccion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_direccion2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_usuariosLayout = new javax.swing.GroupLayout(jp_usuarios);
        jp_usuarios.setLayout(jp_usuariosLayout);
        jp_usuariosLayout.setHorizontalGroup(
            jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_usuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_usuariosLayout.createSequentialGroup()
                        .addGroup(jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jp_usuariosLayout.createSequentialGroup()
                                .addComponent(lbl_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jp_usuariosLayout.createSequentialGroup()
                                .addComponent(lbl_dni, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jp_usuariosLayout.createSequentialGroup()
                                        .addComponent(txt_dni, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 133, Short.MAX_VALUE))
                                    .addComponent(lbl_message, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(372, 372, 372))
                    .addGroup(jp_usuariosLayout.createSequentialGroup()
                        .addGroup(jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jp_usuariosLayout.createSequentialGroup()
                                .addComponent(lbl_direccion2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_direccion2))
                            .addGroup(jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jp_usuariosLayout.createSequentialGroup()
                                    .addGap(196, 196, 196)
                                    .addComponent(jLUsuario))
                                .addGroup(jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jp_usuariosLayout.createSequentialGroup()
                                        .addComponent(lbl_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jp_usuariosLayout.createSequentialGroup()
                                        .addComponent(lbl_direccion1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_direccion1)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jp_usuariosLayout.setVerticalGroup(
            jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_usuariosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_message, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_dni, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_dni, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_direccion1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_direccion1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_direccion2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_direccion2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btn_update.setText("ACTUALIZAR");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_insert.setText("INSERTAR");
        btn_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertActionPerformed(evt);
            }
        });

        btn_delete.setText("ELIMINAR");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_usuarioLayout = new javax.swing.GroupLayout(jp_usuario);
        jp_usuario.setLayout(jp_usuarioLayout);
        jp_usuarioLayout.setHorizontalGroup(
            jp_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sp_contenedor)
            .addGroup(jp_usuarioLayout.createSequentialGroup()
                .addComponent(jp_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jp_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_update, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_delete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
            .addGroup(jp_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_usuarioLayout.createSequentialGroup()
                    .addContainerGap(736, Short.MAX_VALUE)
                    .addComponent(btn_insert, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20)))
        );
        jp_usuarioLayout.setVerticalGroup(
            jp_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_usuarioLayout.createSequentialGroup()
                .addGroup(jp_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_usuarioLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jp_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sp_contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
            .addGroup(jp_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jp_usuarioLayout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(btn_insert, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(439, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_usuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_apellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_apellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_apellidosActionPerformed

    private void btn_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertActionPerformed
        this.guardarUsuario();
    }//GEN-LAST:event_btn_insertActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
       Usuario _user = new Usuario();
       this.btn_insert.setEnabled(false);
       _user.consultar(this.txt_dni.getText());
       if(_user.getNombre()== null ||_user.getNombre().equals("")){
           this.lbl_message.setVisible(true);
       }else{
           this.lbl_message.setVisible(false);
            this.txt_dni.setText(_user.getDni());
            this.txt_nombre.setText(_user.getNombre());
            this.txt_apellidos.setText(_user.getApellidos());
            this.txt_direccion1.setText(_user.getDireccion1());
            this.txt_direccion2.setText(_user.getDireccion2());        
       }
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        
        Usuario _user = new Usuario();
        
       /* if(_user.delete(this.txt_dni.getText())){
            this.clearForm();
            this.cargar_datos();
            this.btn_insert.setEnabled(true);
            JOptionPane.showMessageDialog(null, "Se ha eliminado correctamente",
                "Válido", JOptionPane.PLAIN_MESSAGE); 
            
        }else{
            JOptionPane.showMessageDialog(null, "No se ha eliminado el registro",
                "Error", JOptionPane.ERROR_MESSAGE); 
        }*/
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        Usuario _user =  new Usuario(this.txt_dni.getText(),this.txt_nombre.getText(),
                                    this.txt_apellidos.getText(),this.txt_direccion1.getText(),
                                    this.txt_direccion2.getText());
        if(_user.update()){
            this.clearForm();
            this.cargar_datos();
            this.btn_insert.setEnabled(true);
            JOptionPane.showMessageDialog(null, "Se ha actualizado el usuario correctamente",
                "Válido", JOptionPane.PLAIN_MESSAGE); 
            
        }else{
            JOptionPane.showMessageDialog(null, "No se ha completado la actualizacion de los datos de los usuarios",
                "Error", JOptionPane.ERROR_MESSAGE); 
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void txt_direccion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_direccion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_direccion1ActionPerformed

    private void txt_direccion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_direccion2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_direccion2ActionPerformed

    private void txt_dniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dniActionPerformed
public boolean guardarUsuario(){
   
    
      this.user = new Usuario(this.txt_dni.getText(),this.txt_nombre.getText(),
                            this.txt_apellidos.getText(),this.txt_direccion1.getText(),
                            this.txt_direccion2.getText());
      //validar campos vacios
      boolean valid = user.validarUsuario();
     boolean _res = false;
     System.out.println(user.toString()+ "\n valid "+valid);
     
     if( user.validarDni()){
        if( user.insert()){
            JOptionPane.showMessageDialog(null, "Se ha creado correctamente",
                "Válido", JOptionPane.PLAIN_MESSAGE); 
            _res= true;
        }else{
             JOptionPane.showMessageDialog(null, "No se ha creado correctamente",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
     
     }else{
        JOptionPane.showMessageDialog(null, "Ingrese un dni valido",
                "Error", JOptionPane.ERROR_MESSAGE);
     }
     
    return _res;

}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_insert;
    private javax.swing.JButton btn_update;
    private javax.swing.JLabel jLUsuario;
    private javax.swing.JPanel jp_usuario;
    private javax.swing.JPanel jp_usuarios;
    private javax.swing.JLabel lbl_apellidos;
    private javax.swing.JLabel lbl_direccion1;
    private javax.swing.JLabel lbl_dni;
    private javax.swing.JLabel lbl_message;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JScrollPane sp_contenedor;
    private javax.swing.JTable tb_usuarios;
    private javax.swing.JTextField txt_apellidos;
    private javax.swing.JTextField txt_direccion1;
    private javax.swing.JTextField txt_direccion2;
    private javax.swing.JTextField txt_dni;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
